name: Release

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      package-name: ${{ steps.pack.outputs.package }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - id: pack
        run: echo "package=$(npm pack)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v7
        with:
          name: build-package
          path: ${{ steps.pack.outputs.package }}

  integration-test:
    needs: [build]
    uses: ./.github/workflows/integration-test.yml
    with:
      package-name: ${{ needs.build.outputs.package-name }}
    secrets:
      HARDPOINT_ORG_ID: ${{ secrets.HARDPOINT_ORG_ID }}

  release:
    needs: [integration-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
