name: NPM Release

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - id: pack
        run: echo "package=$(npm pack)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v7
        with:
          name: build-package
          path: ${{ steps.pack.outputs.package }}

  integration-test:
    needs: [build]
    uses: ./.github/workflows/integration-test.yml
    secrets:
      HARDPOINT_ORG_ID: ${{ secrets.HARDPOINT_ORG_ID }}

  publish-npm:
    needs: [integration-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish
