name: Release

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      package-name: ${{ steps.pack.outputs.package }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - id: pack
        run: echo "package=$(npm pack)" >> $GITHUB_OUTPUT
        working-directory: packages/sdk
      - run: cp packages/sdk/${{ steps.pack.outputs.package }} .
      - uses: actions/upload-artifact@v7
        with:
          name: build-package
          path: ${{ steps.pack.outputs.package }}

  integration-test:
    needs: [build]
    uses: ./.github/workflows/integration-test.yml
    with:
      package-name: ${{ needs.build.outputs.package-name }}
    secrets:
      HARDPOINT_ORG_ID: ${{ secrets.HARDPOINT_ORG_ID }}

  release:
    needs: [integration-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
